config/routes.rb
Rails.application.routes.draw do
  root to: 'words#index'
  resources :words, only: [:index, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :first_word, class_name: 'Word'
  belongs_to :second_word, class_name: 'Word'
end

app/models/word.rb
class Word < ApplicationRecord
  has_many :first_word_associations, foreign_key: :first_word_id,
    class_name: 'Relationship'
  has_many :first_associations, through: :first_word_associations,
    source: :second_word
  has_many :second_word_associations, foreign_key: :second_word_id,
    class_name: 'Relationship'
  has_many :second_associations, through: :second_word_associations,
    source: :first_word

  validates :name, presence: true, uniqueness: true

  def associations
    (first_associations + second_associations).flatten.uniq
  end

  def to_param
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/words_controller.rb
# frozen_string_literal: true

class WordsController < ApplicationController
  def index; end

  def create
    if params[:name].present?
      word = CreateWordService.perform(params[:name]&.downcase)

      if word.errors.empty?
        @graph_data = WordGraphExporter.perform(word)
        render json: @graph_data
      end
    end
  end

  private

  def word
    Word.find_by(name: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StilingueChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/5.9.2/d3.min.js"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/words/index.html.erb
<div class="app">
  <div class="title-app">
    <h1>Digite a palavra que voce deseja</h1>
  </div>
  <%= form_with url: words_path, html: { class: "search-box" } do |f| %>
    <%= f.text_field :name, class: "search-txt", required: true %>
    <button type="submit" class="search-btn">
      <i class="fas fa-search"></i>
    </button>
  <% end %>
  <div class="graph-container">
    <div class="whirly-loader"></div> 
  </div>
</div>